# Generated by Django 6.0.1 on 2026-06-09 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BroadcastSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_label", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("venue_name", models.CharField(max_length=200)),
                ("address_line1", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(default="NC", max_length=2)),
                ("zip", models.CharField(max_length=10)),
                ("locality", models.CharField(max_length=40)),
                ("categories", models.JSONField(default=list)),
                ("event_url", models.URLField(blank=True)),
                ("ticket_url", models.URLField(blank=True)),
                ("price", models.CharField(blank=True, max_length=60)),
                ("is_free", models.BooleanField(default=False)),
                ("image_url", models.URLField(blank=True)),
                ("organizer_name", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_key", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("needs_manual", "Needs manual"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("external_url", models.URLField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("screenshot_path", models.CharField(blank=True, max_length=300)),
                ("dry_run", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="broadcast.broadcastsubmission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "site_key"), name="uniq_submission_site"
                    )
                ],
            },
        ),
    ]
