# Generated by Django 6.0.1 on 2026-06-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastsubmission",
            name="event_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="broadcastsubmission",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="broadcastsubmission",
            name="ticket_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="broadcasttarget",
            name="external_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
