# Generated by Django 6.0.1 on 2026-06-13 03:45

import json

from django.db import migrations, models


def locality_str_to_list(apps, schema_editor):
    """Wrap any existing string locality values in a list before the type change."""
    db = schema_editor.connection
    with db.cursor() as cursor:
        cursor.execute("SELECT id, locality FROM broadcast_broadcastsubmission")
        rows = cursor.fetchall()
        for row_id, locality in rows:
            if isinstance(locality, str):
                cursor.execute(
                    "UPDATE broadcast_broadcastsubmission SET locality = %s WHERE id = %s",
                    [json.dumps([locality]), row_id],
                )


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0002_alter_broadcastsubmission_event_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastsubmission",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(locality_str_to_list, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="broadcastsubmission",
            name="locality",
            field=models.JSONField(default=list),
        ),
    ]
