# Generated by Django 6.0.1 on 2026-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0003_locality_jsonfield_city_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
