# Generated by Django 6.0.1 on 2026-07-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0005_accesscode_broadcastaccess_accesscodeuse"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscode",
            name="kind",
            field=models.CharField(
                choices=[
                    ("trial", "Trial (anonymous)"),
                    ("upgrade", "Upgrade (account)"),
                ],
                default="trial",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AccessCodeRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="broadcast.accesscode",
                    ),
                ),
            ],
            options={
                "unique_together": {("access_code", "email")},
            },
        ),
    ]
