# Generated by Django 6.0.1 on 2026-07-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0006_accesscode_kind_accesscoderedemption"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesCodeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("trial", "Free trial"),
                            ("tier1", "Tier 1"),
                            ("tier2", "Tier 2"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("raw_code", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_slot",
                        to="broadcast.accesscode",
                    ),
                ),
            ],
        ),
    ]
