# Generated by Django 6.0.1 on 2026-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0007_salescodeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscode",
            name="code",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
