# Generated by Django 6.0.1 on 2026-07-26 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0009_seed_orphan_recovery_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="broadcast/%Y/%m/")),
                ("client_label", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
