# Generated by Django 6.0.1 on 2026-01-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="city",
            new_name="town",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="venue_name",
            new_name="venue",
        ),
    ]
