# Generated by Django 6.0.1 on 2026-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_city_event_town_rename_venue_name_event_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
