# Generated by Django 6.0.1 on 2026-05-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_add_town_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
