# Generated by Django 6.0.1 on 2026-05-27 21:44

from django.db import migrations, models

SEED_CATEGORIES = [
    ("music", "Music"),
    ("art", "Art"),
    ("food-drink", "Food & Drink"),
    ("sports-outdoors", "Sports & Outdoors"),
    ("community", "Community"),
    ("nightlife", "Nightlife"),
    ("markets-fairs", "Markets & Fairs"),
    ("comedy", "Comedy"),
    ("wellness", "Wellness"),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    for slug, display_name in SEED_CATEGORIES:
        Category.objects.get_or_create(slug=slug, defaults={"display_name": display_name})


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    Category.objects.filter(slug__in=[s for s, _ in SEED_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_fix_betterauth_fk_column_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.category"
            ),
        ),
        migrations.RunPython(seed_categories, reverse_code=unseed_categories),
    ]
