"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
from corsheaders.defaults import default_headers

from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#For Vercel
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-temp-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.vercel.app']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'corsheaders',
    'rest_framework',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "events.apps.EventsConfig",
    "ingestion.apps.IngestionConfig",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:3000",
    "https://www.thecommons.town",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "content-type",
    "authorization",
    "x-csrftoken",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "ingestion" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Ingestion pipeline
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
CRON_SECRET = os.environ.get('CRON_SECRET', '')

# Django Unfold Admin Configuration
# Docs: https://github.com/unfoldadmin/django-unfold
UNFOLD = {
    # Browser tab title
    "SITE_TITLE": "The Commons Admin",

    # Header text shown in the admin top bar
    "SITE_HEADER": "The Commons Admin",

    # Subheader below the site header (smaller text)
    "SITE_SUBHEADER": None,

    # URL the site header links to
    "SITE_URL": "https://www.thecommons.town",

    # Material Symbols icon name for the site header
    # Browse icons: https://fonts.google.com/icons
    "SITE_SYMBOL": None,

    # Path to a logo image (replaces SITE_HEADER text + SITE_SYMBOL)
    "SITE_LOGO": None,

    # Favicon path
    "SITE_FAVICONS": [],

    # Show/hide the search bar in the admin header
    "SHOW_HEADER_SEARCH": True,

    # Show/hide the language switcher
    "SHOW_LANGUAGES": False,

    # Environment banner shown in the header (e.g. "Development", "Production")
    # "ENVIRONMENT": "sample_app.environment_callback",

    # Primary color theme — provide a full Tailwind color scale (50-950)
    # Use https://uicolors.app to generate from a single hex
    # "COLORS": {
    #     "primary": {
    #         "50": "...",
    #         "100": "...",
    #         "200": "...",
    #         "300": "...",
    #         "400": "...",
    #         "500": "...",
    #         "600": "...",
    #         "700": "...",
    #         "800": "...",
    #         "900": "...",
    #         "950": "...",
    #     },
    # },

    # Custom sidebar navigation — groups models into labeled sections with icons
    # Icons use Material Symbols names: https://fonts.google.com/icons
    # "SIDEBAR": {
    #     "navigation": [
    #         {
    #             "title": "Section Title",
    #             "items": [
    #                 {
    #                     "title": "Link Label",
    #                     "link": "/admin/app/model/",
    #                     "icon": "icon_name",
    #                     # "badge": "callback.path",  # optional dynamic badge
    #                     # "permission": "callback.path",  # optional visibility check
    #                 },
    #             ],
    #         },
    #     ],
    # },

    # Tabs displayed on model detail/change pages
    # "TABS": [
    #     {
    #         "models": ["app.modelname"],
    #         "items": [
    #             {"title": "Tab Label", "link": "/admin/app/model/"},
    #         ],
    #     },
    # ],
}
