# Generated by Django 6.0.1 on 2026-03-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_rename_city_event_town_rename_venue_name_event_venue"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ics", "ICS/iCal Feed"),
                            ("scraper", "Web Scraper"),
                            ("email", "Email Inbox"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("active", models.BooleanField(default=True)),
                ("last_polled", models.DateTimeField(blank=True, null=True)),
                ("poll_interval_hours", models.IntegerField(default=24)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_title", models.CharField(max_length=500)),
                ("raw_description", models.TextField(blank=True)),
                ("raw_location", models.CharField(blank=True, max_length=500)),
                ("raw_start", models.DateTimeField()),
                ("raw_end", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("source_uid", models.CharField(blank=True, max_length=500)),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_events",
                        to="ingestion.eventsource",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "source_uid")},
            },
        ),
        migrations.CreateModel(
            name="StagedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("location_name", models.CharField(max_length=255)),
                ("town", models.CharField(max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="ingestion.stagedevent",
                    ),
                ),
                (
                    "published_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staged_source",
                        to="events.event",
                    ),
                ),
                (
                    "raw_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged",
                        to="ingestion.rawevent",
                    ),
                ),
            ],
        ),
    ]
