# Generated by Django 6.0.1 on 2026-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedevent",
            name="link",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="stagedevent",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
