# Generated by Django 6.0.1 on 2026-03-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_stagedevent_link_stagedevent_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagedevent",
            name="raw_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staged",
                to="ingestion.rawevent",
            ),
        ),
    ]
