# Generated by Django 6.0.1 on 2026-05-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0003_stagedevent_raw_event_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedevent",
            name="safety_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stagedevent",
            name="safety_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
