# Generated by Django 6.0.1 on 2026-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0005_stagedevent_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedevent",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
