# Generated by Django 6.0.1 on 2026-07-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0009_eventsource_direct_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsource",
            name="prompt_suffix",
            field=models.TextField(blank=True, default=""),
        ),
    ]
