# Generated by Django 6.0.1 on 2026-07-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0010_eventsource_prompt_suffix"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsource",
            name="scraper_key",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
