# Generated by Django 6.0.1 on 2026-07-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0012_seed_scrape_beat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("ics", "ICS/iCal Feed"),
                    ("scraper", "Web Scraper"),
                    ("http", "HTTP Fetch"),
                    ("email", "Email Inbox"),
                    ("direct", "Direct Host Submission"),
                ],
                max_length=20,
            ),
        ),
    ]
