# Generated by Django 6.0.1 on 2026-07-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0013_alter_eventsource_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("failed", "Failed"),
                            ("refused", "Refused"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("probe", "Probe"),
                            ("manual", "Manual"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("items_fetched", models.IntegerField(default=0)),
                ("items_new", models.IntegerField(default=0)),
                ("items_duplicate", models.IntegerField(default=0)),
                ("error_class", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ingestion.eventsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"],
                        name="ingestion_s_source__a2e121_idx",
                    )
                ],
            },
        ),
    ]
