# Generated by Django 6.0.1 on 2026-07-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0014_sourcerun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagedevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("duplicate", "Duplicate"),
                    ("published", "Published"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
