# Generated by Django 6.0.1 on 2026-07-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0016_stagedevent_skipped_no_town"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawevent",
            name="raw_organizer",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
