# Generated by Django 6.0.1 on 2026-08-03 03:32
#
# 45.4 + 45.7 land together because both add fields to EventSource:
# `default_town` (per-source fallback town for blank Gemini guesses — see
# `ingestion.services.resolve_town`) and `blocked_reason`/`blocked_since`
# (known-blocked quarantine flag — see `devtools.monitoring.source_health`).
# Neither ships prod data; populating them on existing sources is a separate
# ops step.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_seed_wake_forest_town"),
        ("ingestion", "0018_alter_stagedevent_submitted_by_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsource",
            name="blocked_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="eventsource",
            name="blocked_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventsource",
            name="default_town",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_sources",
                to="events.town",
            ),
        ),
    ]
