# Generated by Django 6.0.1 on 2026-08-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0019_eventsource_default_town_and_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagedevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("duplicate", "Duplicate"),
                    ("published", "Published"),
                    ("skipped_no_town", "Skipped — No Matching Town"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
