# Generated by Django 6.0.1 on 2026-08-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0020_alter_stagedevent_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawevent",
            old_name="raw_end",
            new_name="raw_end_datetime",
        ),
        migrations.RenameField(
            model_name="rawevent",
            old_name="raw_start",
            new_name="raw_start_datetime",
        ),
    ]
