# Generated by Django 6.0.1 on 2026-08-05 05:17
#
# 49.11-schema: widen the staged-event category surface. `category` (a single
# CharField) is dropped in favor of `categories` (JSONField, mirroring
# `tags`) so a later ticket can populate multiple slugs per event.
#
# Drop-and-add rather than a rename: the type changes (str -> list), so a
# straight rename would leave every existing row's stringy value sitting in a
# JSONField without ever being valid JSON. No explicit RunPython backfill is
# needed either way — all 647 existing rows have `category=""`, and
# `AddField`'s `default=list` already gives the new column `[]` for every one
# of them, which is the correct "no categories yet" equivalent of `""`.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0021_rename_raw_end_rawevent_raw_end_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagedevent",
            name="category",
        ),
        migrations.AddField(
            model_name="rawevent",
            name="raw_categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="stagedevent",
            name="categories",
            field=models.JSONField(default=list),
        ),
    ]
