# Generated by Django 6.0.1 on 2026-08-05 19:44

"""Suite 50: drop the staged-event category surface added by 49.11-schema.

Removes `RawEvent.raw_categories` and `StagedEvent.categories`. ⚠️ One-way —
the JSON payloads are dropped outright. Pairs with events.0026, which deletes
the Category model itself.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0022_widen_staged_event_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawevent",
            name="raw_categories",
        ),
        migrations.RemoveField(
            model_name="stagedevent",
            name="categories",
        ),
    ]
